name: Daily Job Scraper

on:
  schedule:
    # Runs every day at 6:00 AM UTC (adjust time as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Prevent long-running jobs
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up Chrome for Selenium
      uses: browser-actions/setup-chrome@latest
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@master
    
    - name: Run job scraper
      run: |
        echo "Starting job scraper..."
        python start.py
        echo "Job scraper completed"
      env:
        PYTHONUNBUFFERED: 1
    
    - name: Check for generated files
      run: |
        echo "Generated files:"
        ls -la *.json *.csv || echo "No JSON/CSV files found"
    
    - name: Configure git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push changes
      run: |
        git add *.json *.csv || echo "No files to add"
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing changes..."
          git commit -m "Daily job scrape - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
          echo "Changes pushed successfully"
        fi